# math_config.py

dstart = '2011'
dend = '2012'

cat = 'math'

math_branches = [
    "Algebra",
    "Geometry",
    "Calculus",
    "Number Theory",
    "Topology",
    "Analysis",
    "Probability",
    "Statistics",
    "Combinatorics",
    "Linear Algebra",
    "Differential Equations",
    "Mathematical Logic",
    "Graph Theory",
    "Set Theory",
    "Numerical Analysis",
    "Optimization",
    "Cryptography",
    "Game Theory",
    "Dynamical Systems",
    "Complex Analysis"
]

math_connections = [
    "Algebraic Geometry",
    "Analytic Number Theory",
    "Algebraic Topology",
    "Geometric Analysis",
    "Stochastic Calculus",
    "Algebraic Combinatorics",
    "Statistical Learning Theory",
    "Computational Geometry",
    "Topological Data Analysis",
    "Algebraic Number Theory",
    "Differential Geometry",
    "Functional Analysis",
    "Arithmetic Geometry",
    "Geometric Topology",
    "Probabilistic Number Theory",
    "Algebraic Graph Theory",
    "Geometric Probability",
    "Analytical Combinatorics",
    "Algebraic Statistics",
    "Topological Algebra",
    "Geometric Group Theory",
    "Spectral Graph Theory",
    "Tropical Geometry",
    "Algebraic Logic",
    "Categorical Logic",
    "Quantum Topology",
    "Symplectic Geometry",
    "Arithmetic Dynamics",
    "Algebraic K-theory",
    "Geometric Measure Theory"
]

math_science_connections = [
    "Quantum Mechanics",
    "Statistical Mechanics",
    "Computational Biology",
    "Econometrics",
    "Bioinformatics",
    "Astrophysics",
    "Fluid Dynamics",
    "Geophysics",
    "Biomathematics",
    "Chemometrics",
    "Neuroinformatics",
    "Psychometrics",
    "Financial Mathematics",
    "Computational Chemistry",
    "Biostatistics",
    "Mathematical Physics",
    "Systems Biology",
    "Climatology",
    "Quantitative Genetics",
    "Biophysics",
    "Computational Neuroscience",
    "Mathematical Ecology",
    "Astrodynamics",
    "Quantum Computing",
    "Crystallography",
    "Population Genetics",
    "Signal Processing",
    "Operations Research",
    "Epidemiology",
    "Cryptography"
]

allcats = [
    "cs",
    "econ",
    "eess",
    "math",
    "physics",
    "physics:astro-ph",
    "physics:cond-mat",
    "physics:gr-qc",
    "physics:hep-ex",
    "physics:hep-lat",
    "physics:hep-ph",
    "physics:hep-th",
    "physics:math-ph",
    "physics:nlin",
    "physics:nucl-ex",
    "physics:nucl-th",
    "physics:physics",
    "physics:quant-ph",
    "q-bio",
    "q-fin",
    "stat"
 ]
